openapi: 3.0.3
info:
  title: Lead Management API
  description: API for managing leads, templates, promotions, messages, attachments, email verifications, and SMS OTPs
  version: 1.0.0
servers:
  - url: https://franchisee-lead-management-server.onrender.com/api
    description: Franchise Lead Managements Server
paths:
  /leads:
    get:
      summary: Get all leads
      responses:
        "200":
          description: List of leads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lead"
        "500":
          description: Failed to fetch leads
  /leads/search:
    get:
      summary: Search leads
      parameters:
        - name: query
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of matching leads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lead"
        "500":
          description: Failed to search leads
  /leads/{id}:
    get:
      summary: Get lead by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Lead details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lead"
        "404":
          description: Lead not found
        "500":
          description: Failed to fetch lead
  /templates:
    get:
      summary: Get all templates
      parameters:
        - name: type
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Template"
        "500":
          description: Failed to fetch templates
    post:
      summary: Create a new template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateInput"
      responses:
        "201":
          description: Template created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        "400":
          description: Missing required fields
        "500":
          description: Failed to save template
  /templates/{id}:
    get:
      summary: Get template by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Template details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        "404":
          description: Template not found
        "500":
          description: Failed to fetch template
    put:
      summary: Update a template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateInput"
      responses:
        "200":
          description: Template updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        "400":
          description: Missing required fields
        "500":
          description: Failed to update template
    delete:
      summary: Delete a template
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Template deleted
        "500":
          description: Failed to delete template
  /promotions:
    get:
      summary: Get all promotions
      responses:
        "200":
          description: List of promotions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Promotion"
        "500":
          description: Failed to fetch promotions
    post:
      summary: Create a new promotion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromotionInput"
      responses:
        "201":
          description: Promotion created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Promotion"
        "400":
          description: Missing required fields
        "500":
          description: Failed to create promotion
  /promotions/{id}:
    get:
      summary: Get promotion details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Promotion details with leads and attachments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PromotionDetails"
        "404":
          description: Promotion not found
        "500":
          description: Failed to fetch promotion details
  /promotions/{id}/leads:
    post:
      summary: Add leads to a promotion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lead_ids:
                  type: array
                  items:
                    type: integer
              required: ["lead_ids"]
      responses:
        "201":
          description: Leads added to promotion
        "400":
          description: Lead IDs array required
        "404":
          description: Promotion not found
        "500":
          description: Failed to add leads
  /messages/send:
    post:
      summary: Send messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                promotion_id:
                  type: integer
                lead_ids:
                  type: array
                  items:
                    type: integer
                type:
                  type: string
                content:
                  type: string
              required: ["promotion_id", "lead_ids", "type", "content"]
      responses:
        "201":
          description: Messages sent
        "400":
          description: Missing required fields
        "500":
          description: Failed to send messages
  /messages/schedule:
    post:
      summary: Schedule messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                subject:
                  type: string
                body:
                  type: string
                lead_ids:
                  type: array
                  items:
                    type: integer
                scheduled_date:
                  type: string
                  format: date-time
              required: ["name", "type", "body", "lead_ids", "scheduled_date"]
      responses:
        "201":
          description: Messages scheduled
        "400":
          description: Missing required fields
        "500":
          description: Failed to schedule messages
  /attachments:
    post:
      summary: Upload an attachment
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: The file to upload
        - in: formData
          name: promotion_id
          type: integer
          description: ID of the associated promotion
      responses:
        "201":
          description: Attachment uploaded
        "400":
          description: Missing required fields
        "500":
          description: Failed to upload attachment
  /email/verify:
    post:
      summary: Verify if an email domain is disposable or invalid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required: ["email"]
      responses:
        "200":
          description: Email verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  is_disposable:
                    type: boolean
        "400":
          description: Invalid email format
        "500":
          description: Failed to verify email
  /verifications/email:
    post:
      summary: Save email verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lead_id:
                  type: integer
                email:
                  type: string
                status:
                  type: string
                score:
                  type: integer
                issue:
                  type: string
              required: ["email", "status"]
      responses:
        "201":
          description: Email verification saved
        "400":
          description: Missing required fields
        "500":
          description: Failed to save email verification
  /sms/send-otp:
    post:
      summary: Send OTP via SMS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendOtpInput"
      responses:
        "200":
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OTP sent successfully
        "400":
          description: Missing required fields
        "500":
          description: Failed to send OTP
components:
  schemas:
    Lead:
      type: object
      properties:
        id:
          type: integer
        name_of_lead:
          type: string
        city:
          type: string
        state:
          type: string
        contact_number:
          type: string
        email_id:
          type: string
        franchise_developer_name:
          type: string
        status:
          type: string
        leadType:
          type: string
    Template:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        subject:
          type: string
        body:
          type: string
        created_by:
          type: integer
    TemplateInput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        subject:
          type: string
        body:
          type: string
        created_by:
          type: integer
      required: ["name", "type", "body"]
    Promotion:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        status:
          type: string
        scheduled_date:
          type: string
          format: date-time
        created_by:
          type: integer
        specialty:
          type: string
        subject:
          type: string
        body:
          type: string
    PromotionInput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        status:
          type: string
        scheduled_date:
          type: string
          format: date-time
        created_by:
          type: integer
        specialty:
          type: string
        subject:
          type: string
        body:
          type: string
      required: ["name", "type", "status"]
    PromotionDetails:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        status:
          type: string
        scheduled_date:
          type: string
          format: date-time
        created_by:
          type: integer
        specialty:
          type: string
        subject:
          type: string
        body:
          type: string
        leads:
          type: array
          items:
            $ref: "#/components/schemas/Lead"
        attachments:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              file_name:
                type: string
              file_type:
                type: string
              file_size:
                type: integer
    SendOtpInput:
      type: object
      properties:
        phoneNumber:
          type: string
          description: The phone number to send the OTP to (in international format, e.g., +1234567890)
      required: ["phoneNumber"]
